Repository celestiaorg/go-header, pull requests merged in 2023-04, with the labels that each got.

#23 refactor: reduce empty response to DEBUG log
  p2p/session.go
Labels: kind:misc

#18 feat: add README.md + Makefile + lint, test and generate coverage
  .gitignore
  .markdownlint.yaml
  Makefile
  README.md
  p2p/exchange_test.go
  p2p/helpers.go
  p2p/server.go
Labels: kind:misc

#26 fix: avoid replacing proto dep and add pb-gen makefile rule
  Makefile
  go.mod
  go.sum
Labels: kind:fix

#29 chore(p2p): remove TrustedPeersRequestTimeout config field
  p2p/exchange.go
  p2p/options.go
Labels: kind:chore

#31 feat: WithParams option for every component
  p2p/options.go
  p2p/options_test.go
  store/options.go
  store/options_test.go
  sync/options.go
  sync/options_test.go
Labels: kind:feat

#33 refactor(p2p): Peer tracker respects context on Stop
  p2p/exchange.go
  p2p/peer_tracker.go
  p2p/peer_tracker_test.go
Labels: kind:refactor
