Repository celestiaorg/go-header, pull requests merged in 2023-07, with the labels that each got.

#64 fix(sync): fix two synchronization issues
  p2p/exchange_test.go
  sync/sync.go
  sync/sync_getter.go
  sync/sync_getter_test.go
  sync/sync_head.go
  sync/sync_head_test.go
Labels: kind:fix

#69 fix(store): make storePrefix actually optional
  store/options.go
  store/store.go
Labels: kind:fix

#71 bugfix: fix panic in GetVerifiedRange
  store/store.go
  store/store_test.go
Labels: store, kind:fix

#73 fix(store): ensure Store can be initialized with any height
  store/heightsub.go
  store/store_test.go
Labels: kind:fix

#81 bug(sync): change error type to string
  sync/sync.go
Labels: bug, syncer

#77 chore(sync): Rename a variable inside sync_getter for better readability
  sync/sync_getter.go
Labels: kind:misc

#82 feat(sync): add json tags
  sync/sync.go
Labels: syncer, kind:misc

#83 fix: fix issue with error restoring in syncer
  sync/sync.go
Labels: syncer, kind:fix

#84 chore(deps): bump otel
  go.mod
  go.sum
  metrics.go
  p2p/metrics.go
  sync/metrics.go
Labels: kind:deps

#76 test(sync): Test case where bad header is set as sync target
  headertest/dummy_header.go
  sync/sync_test.go
Labels: kind:chore
