Repository celestiaorg/go-header, pull requests merged in 2023-08, with the labels that each got.

#88 refactor!: Subcriber: AddValidator -> SetVerifier
  errors.go
  headertest/subscriber.go
  interface.go
  p2p/subscriber.go
  p2p/subscription_test.go
  sync/sync.go
  sync/sync_head.go
  sync/sync_head_test.go
  sync/sync_test.go
Labels: kind:break!, kind:refactor

#89 fix: ensure header.Validate is called by the lib
  header.go
  p2p/exchange.go
  p2p/session.go
  p2p/session_test.go
  p2p/subscriber.go
  store/init.go
  store/store.go
Labels: kind:fix, kind:refactor

#95 chore: bump deps to support go1.21
  .github/workflows/go-ci.yml
  Makefile
  go.mod
  go.sum
Labels: kind:chore

#90 refactor!: harden verification
  Makefile
  errors.go
  headertest/dummy_header.go
  headertest/dummy_suite.go
  headertest/verify_test.go
  p2p/exchange_test.go
  p2p/helpers.go
  p2p/server.go
  p2p/subscriber.go
  store/heightsub_test.go
  sync/sync_head.go
  sync/sync_test.go
  verify.go
Labels: kind:break!, kind:refactor

#96 refactor!: type paramed Header interface
  header.go
  headertest/dummy_header.go
  headertest/store.go
  headertest/subscriber.go
  interface.go
  local/exchange.go
  metrics.go
  opts.go
  p2p/exchange.go
  p2p/exchange_test.go
  p2p/server.go
  p2p/session.go
  p2p/subscriber.go
  p2p/subscription.go
  store/batch.go
  store/height_indexer.go
  store/heightsub.go
  store/init.go
  store/keys.go
  store/store.go
  sync/ranges.go
  sync/sync.go
  sync/sync_getter.go
  sync/sync_getter_test.go
  sync/sync_head.go
  sync/sync_head_test.go
  sync/sync_store.go
  sync/sync_test.go
  verify.go
Labels: kind:refactor

#101 fix!: remove lifecycle methods from the interface
  headertest/store.go
  interface.go
Labels: kind:break!, kind:fix

#97 fix(sync): Allow some more slack for recency estimation
  sync/options.go
  sync/sync_head.go
  sync/sync_head_test.go
  sync/sync_test.go
Labels: kind:fix

#100 refactor!: make Header.Height uint64
  header.go
  headertest/dummy_header.go
  headertest/store.go
  interface.go
  metrics.go
  p2p/exchange_test.go
  p2p/server.go
  store/batch.go
  store/height_indexer.go
  store/heightsub.go
  sync/sync_head.go
  sync/sync_test.go
  verify.go
Labels: kind:break!, kind:refactor
