Repository celestiaorg/go-header, pull requests merged in 2023-10, with the labels that each got.

#113 fix(p2p/exchange): Remove peer blocking from head request
  p2p/exchange.go
Labels: kind:fix

#114 fix(sync): allow a greater buffer for recency threshold default
  sync/sync_head.go
Labels: kind:fix

#117 refactor!: Merge `GetVerifiedRange` and `GetRangeByHeight` in Getter interface and remove redundant endpoint
  headertest/store.go
  interface.go
  local/exchange.go
  p2p/exchange.go
  p2p/exchange_test.go
  p2p/server.go
  p2p/server_test.go
  p2p/session.go
  store/store.go
  store/store_test.go
  sync/sync.go
  sync/sync_getter_test.go
  sync/sync_head_test.go
  sync/sync_test.go
Labels: kind:break!

#121 refactor(sync)!: use options to init metrics
  sync/metrics.go
  sync/options.go
  sync/sync.go
Labels: kind:break!

#123 fix!: handle error on metrics
  p2p/exchange.go
  p2p/metrics.go
  p2p/subscriber.go
  p2p/subscription_test.go
  sync/metrics.go
  sync/sync.go
Labels: kind:break!

#125 feat(p2p): metrics for Exchange
  p2p/exchange.go
  p2p/exchange_metrics.go
  p2p/helpers.go
  p2p/metrics.go
  p2p/peer_stats.go
  p2p/peer_stats_test.go
  p2p/peer_tracker.go
  p2p/peer_tracker_test.go
  p2p/session.go
  p2p/session_test.go
  p2p/subscriber_metrics.go
Labels: kind:feat

#126 feat(p2p): metrics for ExchangeServer
  p2p/server.go
  p2p/server_metrics.go
Labels: kind:feat
