Repository celestiaorg/go-header, pull requests merged in 2024-06, with the labels that each got.

#191 refactor(store,sync)!: drop `NewStoreWithHead`
  store/init_test.go
  store/store.go
  store/store_test.go
  store/testing.go
  sync/sync_head_test.go
  sync/sync_test.go
Labels: kind:break!, kind:refactor

#186 feat(sync, store)!: Remove adjacency requirement from Store.Append
  interface.go
  store/store.go
  sync/sync_head.go
  sync/sync_store.go
Labels: kind:break!, kind:feat

#194 fix(p2p)!: use request timeout
  p2p/exchange.go
  p2p/exchange_test.go
  p2p/options.go
  p2p/options_test.go
  p2p/server.go
  p2p/server_test.go
Labels: kind:break!

#206 refactor(sync): simplify isExpired
  sync/sync_head.go
  sync/sync_test.go
Labels: kind:refactor

#208 doc:improve header.Verify godoc
  header.go
Labels: documentation
