Repository celestiaorg/go-header, pull requests merged in 2025-04, with the labels that each got.

#256 chore: major linting
  .github/workflows/go-ci.yml
  .golangci.yml
  headertest/store.go
  headertest/subscriber.go
  internal/otelattr/attribute_uint64.go
  p2p/exchange.go
  p2p/exchange_metrics.go
  p2p/exchange_test.go
  p2p/helpers.go
  p2p/options.go
  p2p/peer_stats.go
  p2p/peer_stats_test.go
  p2p/peer_tracker.go
  p2p/peer_tracker_test.go
  p2p/server.go
  p2p/server_metrics.go
  p2p/server_test.go
  p2p/session.go
  p2p/subscriber.go
  p2p/subscriber_metrics.go
  p2p/subscription.go
  p2p/subscription_test.go
  store/height_indexer.go
  store/heightsub.go
  store/init.go
  store/keys.go
  store/metrics.go
  store/options.go
  store/store.go
  store/testing.go
  sync/metrics.go
  sync/options.go
  sync/ranges.go
  sync/sync.go
  sync/sync_getter_test.go
  sync/sync_head.go
  sync/sync_head_test.go
  sync/sync_test.go
  verify.go
Labels: kind:chore

#219 feat(sync): bifurcation for syncTarget
  header.go
  headertest/dummy_header.go
  sync/metrics.go
  sync/sync_head.go
  sync/sync_head_test.go
Labels: kind:feat

#261 feat!(store): add Tail
  headertest/store.go
  interface.go
  p2p/server_test.go
  store/keys.go
  store/store.go
  store/store_test.go
Labels: kind:feat

#269 fix(sync): discard headers failed bifurcation
  sync/sync_head.go
  sync/sync_test.go
Labels: kind:fix

#273 fix: add header range mix up check
  interface.go
  p2p/server.go
Labels: kind:fix

#268 refactor: extract VerifyRange and remove verification out of store
  headertest/verify_test.go
  local/exchange.go
  p2p/session.go
  p2p/session_test.go
  store/store.go
  store/store_test.go
  verify.go
Labels: kind:refactor

#275 feat!(store): add DeleteTo and update tail accordingly
  headertest/store.go
  interface.go
  p2p/server_test.go
  store/batch.go
  store/height_indexer.go
  store/keys.go
  store/store.go
  store/store_test.go
Labels: kind:feat

#272 fix(p2p): add correct header length validation
  p2p/session.go
Labels: kind:fix

#278 fix: use proper log functions
  p2p/subscriber.go
  sync/ranges.go
Labels: kind:fix

#279 chore(store): small DeleteTo updates
  store/store.go
Labels: kind:chore
