Repository celestiaorg/go-header, pull requests merged in 2025-05, with the labels that each got.

#286 chore: do lint
  p2p/server.go
  p2p/session.go
  sync/metrics.go
  verify.go
Labels: kind:chore

#283 feat(store): advance tail
  store/metrics.go
  store/store.go
  store/store_test.go
Labels: kind:feat, pruning

#285 fix(store): support complete erase
  store/store.go
  store/store_test.go
Labels: kind:fix, pruning

#281 fix(p2p): do proper msg.ValidatorData handling
  p2p/subscriber.go
  sync/syncsub_test.go
Labels: kind:fix

#288 chore(CODEOWNERS): remove @cristaloleg
  .github/CODEOWNERS
Labels: kind:chore

#265 feat(sync): maintain tail
  headertest/dummy_suite.go
  headertest/store.go
  sync/options.go
  sync/sync.go
  sync/sync_head.go
  sync/sync_store.go
  sync/sync_test.go
  sync/syncer_tail.go
  sync/syncer_tail_test.go
Labels: kind:feat, pruning
